### ISSUE TITLE
Running on Android is not possible because of the dependence on node-libcurl

### ISSUE THREAD

**Issue by ustas-eth** [lens-protocol/momoka#20]
I'm trying to run an instance of the Momoka node on my Android phone with Termux.

Unfortunately, the node-libcurl [doesn't have a prebuild](https://github.com/JCMais/node-libcurl/releases) for Android, so I have to build it from sources. During the build process, it's trying to run postinstall script but fails with an error (see the screenshot).

![Screenshot_20230523-121415_Trebuchet](https://github.com/lens-protocol/momoka/assets/82833595/c3a48418-fc84-45f7-997d-68ffc2d1ad1f)

Can we do something with this, or can the node-libcurl team only fix it?

**Comment by joshstevens19** [comment]
Yeah, so I think this is an issue for a few other OS. I am in 2 minds to remove node-libcurl and use Axios for all this would get rid of this issue fully.. let me think about this and get back to you

**Comment by joshstevens19** [comment]
https://github.com/lens-protocol/momoka/pull/21

should fix this will deploy shortly

**Comment by joshstevens19** [comment]
ok deployed have another go should not have a dependency on lib-curl anymore

**Comment by joshstevens19** [comment]
p.s would love to see this running on a mobile device!

**Comment by ustas-eth** [comment]
Hey! It works! Nice job
