### ISSUE TITLE
How to know mirror from someone's mirror?

### ISSUE THREAD

**Issue by MyJoiT** [lens-protocol/momoka#30]
Hi there. Suppose I post something through Momoka.

PersonA mirrors it from my profile page
PersonB mirrors it from PersonA's profile page
PersonC mirrors it from the PersonB profile page

We cannot know if C's mirror is from B's mirror. Is that right?

I query the Momoka artx and proofs but cannot figure out that.

**Comment by joshstevens19** [comment]
yes mirror is a mirror of the root publication so:

Josh posts we call it post 1
Joi mirrors it we call this mirror 1 which points to post 1
John mirrors mirror 1 we call this mirror 2 but this points to post 1 not mirror 1

**Comment by MyJoiT** [comment]
Thank you. I understand.
