### ISSUE TITLE
Some references to Bonsai left in images

### ISSUE THREAD

**Issue by gpersoon** [lens-protocol/momoka#7]
The following images still contain references to Bonsai:
- https://github.com/lens-protocol/momoka/blob/master/images/submitter-flow.jpg
- https://github.com/lens-protocol/momoka/blob/master/images/decentralized-submitters.jpg

**Comment by joshstevens19** [comment]
thanks fixed

**Comment by gpersoon** [comment]
Thanks, @joshstevens19 

In noticed still one `Generate Bonsai ID` left here:
https://github.com/lens-protocol/momoka/blob/master/images/submitter-flow.jpg

**Comment by joshstevens19** [comment]
Amazing eyes haha we shall fix thanks a lot
